/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Profile {
  'ratingSum' : bigint,
  'totalRatingsCount' : bigint,
  'ratingCount' : bigint,
  'tasksCompleted' : bigint,
  'averageRating' : bigint,
  'earnings' : bigint,
  'tasksPosted' : bigint,
}
export type Stars = { 'one' : null } |
  { 'two' : null } |
  { 'three' : null } |
  { 'five' : null } |
  { 'four' : null };
export interface Task {
  'id' : TaskId,
  'taskPhoto' : ExternalBlob,
  'title' : string,
  'creator' : Principal,
  'isCompleted' : boolean,
  'performer' : [] | [Principal],
  'deadline' : [] | [Time],
  'isVerified' : boolean,
  'safeSpot' : string,
  'telegramDiscussionEnabled' : boolean,
  'category' : string,
  'price' : bigint,
  'location' : string,
  'telegramHandle' : string,
  'verificationPhoto' : [] | [ExternalBlob],
}
export type TaskId = bigint;
export type Time = bigint;
export interface UserProfile {
  'gmailAddress' : [] | [string],
  'name' : string,
  'postHistory' : Array<TaskId>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPerformer' : ActorMethod<[TaskId], undefined>,
  'completeTask' : ActorMethod<[TaskId, ExternalBlob], undefined>,
  'createTask' : ActorMethod<
    [string, string, bigint, string, string, string, ExternalBlob, [] | [Time]],
    TaskId
  >,
  'createUserProfileWithGoogle' : ActorMethod<[string, string], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getCallerProfile' : ActorMethod<[], Profile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForTask' : ActorMethod<[bigint], Array<[string, string, string]>>,
  'getLeaderboard' : ActorMethod<[], Array<Profile>>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getTasksByUser' : ActorMethod<[Principal], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTasks' : ActorMethod<[string], Array<Task>>,
  'toggleTelegramDiscussion' : ActorMethod<[bigint, boolean], undefined>,
  'updateUserProfile' : ActorMethod<[string], undefined>,
  'verifyTask' : ActorMethod<[TaskId, Stars, Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];