/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Profile = IDL.Record({
  'ratingSum' : IDL.Nat,
  'totalRatingsCount' : IDL.Nat,
  'ratingCount' : IDL.Nat,
  'tasksCompleted' : IDL.Nat,
  'averageRating' : IDL.Nat,
  'earnings' : IDL.Nat,
  'tasksPosted' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'gmailAddress' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'postHistory' : IDL.Vec(TaskId),
});
export const Task = IDL.Record({
  'id' : TaskId,
  'taskPhoto' : ExternalBlob,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'isCompleted' : IDL.Bool,
  'performer' : IDL.Opt(IDL.Principal),
  'deadline' : IDL.Opt(Time),
  'isVerified' : IDL.Bool,
  'safeSpot' : IDL.Text,
  'telegramDiscussionEnabled' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'telegramHandle' : IDL.Text,
  'verificationPhoto' : IDL.Opt(ExternalBlob),
});
export const Stars = IDL.Variant({
  'one' : IDL.Null,
  'two' : IDL.Null,
  'three' : IDL.Null,
  'five' : IDL.Null,
  'four' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPerformer' : IDL.Func([TaskId], [], []),
  'completeTask' : IDL.Func([TaskId, ExternalBlob], [], []),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(Time),
      ],
      [TaskId],
      [],
    ),
  'createUserProfileWithGoogle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getCallerProfile' : IDL.Func([], [Profile], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForTask' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'toggleTelegramDiscussion' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateUserProfile' : IDL.Func([IDL.Text], [], []),
  'verifyTask' : IDL.Func([TaskId, Stars, IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Profile = IDL.Record({
    'ratingSum' : IDL.Nat,
    'totalRatingsCount' : IDL.Nat,
    'ratingCount' : IDL.Nat,
    'tasksCompleted' : IDL.Nat,
    'averageRating' : IDL.Nat,
    'earnings' : IDL.Nat,
    'tasksPosted' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'gmailAddress' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'postHistory' : IDL.Vec(TaskId),
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'taskPhoto' : ExternalBlob,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'isCompleted' : IDL.Bool,
    'performer' : IDL.Opt(IDL.Principal),
    'deadline' : IDL.Opt(Time),
    'isVerified' : IDL.Bool,
    'safeSpot' : IDL.Text,
    'telegramDiscussionEnabled' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'telegramHandle' : IDL.Text,
    'verificationPhoto' : IDL.Opt(ExternalBlob),
  });
  const Stars = IDL.Variant({
    'one' : IDL.Null,
    'two' : IDL.Null,
    'three' : IDL.Null,
    'five' : IDL.Null,
    'four' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPerformer' : IDL.Func([TaskId], [], []),
    'completeTask' : IDL.Func([TaskId, ExternalBlob], [], []),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(Time),
        ],
        [TaskId],
        [],
      ),
    'createUserProfileWithGoogle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getCallerProfile' : IDL.Func([], [Profile], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForTask' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'toggleTelegramDiscussion' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateUserProfile' : IDL.Func([IDL.Text], [], []),
    'verifyTask' : IDL.Func([TaskId, Stars, IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };